export const ukrCountryList = [
  {
    name: "Afghanistan",
    numericCode: "004",
    ukrName: "Афганістан",
    ukrNameLowCase: "афганістан",
  },
  {
    name: "Aland Islands",
    numericCode: "248",
    ukrName: "Аландські острови",
    ukrNameLowCase: "аландські острови",
  },
  {
    name: "Albania",
    numericCode: "008",
    ukrName: "Албанія",
    ukrNameLowCase: "албанія",
  },
  {
    name: "Algeria",
    numericCode: "012",
    ukrName: "Алжир",
    ukrNameLowCase: "алжир",
  },
  {
    name: "American Samoa",
    numericCode: "016",
    ukrName: "Американське Самоа",
    ukrNameLowCase: "американське самоа",
  },
  {
    name: "Andorra",
    numericCode: "020",
    ukrName: "Андорра",
    ukrNameLowCase: "андорра",
  },
  {
    name: "Angola",
    numericCode: "024",
    ukrName: "Ангола",
    ukrNameLowCase: "ангола",
  },
  {
    name: "Anguilla",
    numericCode: "660",
    ukrName: "Ангілья",
    ukrNameLowCase: "ангілья",
  },
  {
    name: "Antarctica",
    numericCode: "010",
    ukrName: "Антарктида",
    ukrNameLowCase: "антарктида",
  },
  {
    name: "Antigua and Barbuda",
    numericCode: "028",
    ukrName: "Антигуа і Барбуда",
    ukrNameLowCase: "антигуа і барбуда",
  },
  {
    name: "Argentina",
    numericCode: "032",
    ukrName: "Аргентина",
    ukrNameLowCase: "аргентина",
  },
  {
    name: "Armenia",
    numericCode: "051",
    ukrName: "Вірменія",
    ukrNameLowCase: "вірменія",
  },
  {
    name: "Aruba",
    numericCode: "533",
    ukrName: "Аруба",
    ukrNameLowCase: "аруба",
  },
  {
    name: "Australia",
    numericCode: "036",
    ukrName: "Австралія",
    ukrNameLowCase: "австралія",
  },
  {
    name: "Austria",
    numericCode: "040",
    ukrName: "Австрія",
    ukrNameLowCase: "австрія",
  },
  {
    name: "Azerbaijan",
    numericCode: "031",
    ukrName: "Азербайджан",
    ukrNameLowCase: "азербайджан",
  },
  {
    name: "Bahamas",
    numericCode: "044",
    ukrName: "Багами",
    ukrNameLowCase: "багами",
  },
  {
    name: "Bahrain",
    numericCode: "048",
    ukrName: "Бахрейн",
    ukrNameLowCase: "бахрейн",
  },
  {
    name: "Bangladesh",
    numericCode: "050",
    ukrName: "Бангладеш",
    ukrNameLowCase: "бангладеш",
  },
  {
    name: "Barbados",
    numericCode: "052",
    ukrName: "Барбадос",
    ukrNameLowCase: "барбадос",
  },
  {
    name: "Belarus",
    numericCode: "112",
    ukrName: "Білорусь",
    ukrNameLowCase: "білорусь",
  },
  {
    name: "Belgium",
    numericCode: "056",
    ukrName: "Бельгія",
    ukrNameLowCase: "бельгія",
  },
  {
    name: "Belize",
    numericCode: "084",
    ukrName: "Беліз",
    ukrNameLowCase: "беліз",
  },
  {
    name: "Benin",
    numericCode: "204",
    ukrName: "Бенін",
    ukrNameLowCase: "бенін",
  },
  {
    name: "Bermuda",
    numericCode: "060",
    ukrName: "Бермудські острови",
    ukrNameLowCase: "бермудські острови",
  },
  {
    name: "Bhutan",
    numericCode: "064",
    ukrName: "Бутан",
    ukrNameLowCase: "бутан",
  },
  {
    name: "Bolivia (Plurinational State of)",
    numericCode: "068",
    ukrName: "Болівія (Багатонаціональна Держава)",
    ukrNameLowCase: "болівія (багатонаціональна держава)",
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    numericCode: "535",
    ukrName: "Бонайре, Сінт-Естатіус і Саба",
    ukrNameLowCase: "бонайре, сінт-естатіус і саба",
  },
  {
    name: "Bosnia and Herzegovina",
    numericCode: "070",
    ukrName: "Боснія і Герцеговина",
    ukrNameLowCase: "боснія і герцеговина",
  },
  {
    name: "Botswana",
    numericCode: "072",
    ukrName: "Ботсвана",
    ukrNameLowCase: "ботсвана",
  },
  {
    name: "Bouvet Island",
    numericCode: "074",
    ukrName: "Острів Буве",
    ukrNameLowCase: "острів буве",
  },
  {
    name: "Brazil",
    numericCode: "076",
    ukrName: "Бразилія",
    ukrNameLowCase: "бразилія",
  },
  {
    name: "British Indian Ocean Territory",
    numericCode: "086",
    ukrName: "Британська територія в індійському океані",
    ukrNameLowCase: "британська територія в індійському океані",
  },
  {
    name: "United States Minor Outlying Islands",
    numericCode: "581",
    ukrName: "Віддалені малі острови Сполучених Штатів",
    ukrNameLowCase: "віддалені малі острови сполучених штатів",
  },
  {
    name: "Virgin Islands (British)",
    numericCode: "092",
    ukrName: "Віргінські острови (Британські)",
    ukrNameLowCase: "віргінські острови (британські)",
  },
  {
    name: "Virgin Islands (U.S.)",
    numericCode: "850",
    ukrName: "Віргінські острови (США)",
    ukrNameLowCase: "віргінські острови (сша)",
  },
  {
    name: "Brunei Darussalam",
    numericCode: "096",
    ukrName: "Бруней Даруссалам",
    ukrNameLowCase: "бруней даруссалам",
  },
  {
    name: "Bulgaria",
    numericCode: "100",
    ukrName: "Болгарія",
    ukrNameLowCase: "болгарія",
  },
  {
    name: "Burkina Faso",
    numericCode: "854",
    ukrName: "Буркіна-Фасо",
    ukrNameLowCase: "буркіна-фасо",
  },
  {
    name: "Burundi",
    numericCode: "108",
    ukrName: "Бурунді",
    ukrNameLowCase: "бурунді",
  },
  {
    name: "Cambodia",
    numericCode: "116",
    ukrName: "Камбоджа",
    ukrNameLowCase: "камбоджа",
  },
  {
    name: "Cameroon",
    numericCode: "120",
    ukrName: "Камерун",
    ukrNameLowCase: "камерун",
  },
  {
    name: "Canada",
    numericCode: "124",
    ukrName: "Канада",
    ukrNameLowCase: "канада",
  },
  {
    name: "Cabo Verde",
    numericCode: "132",
    ukrName: "Кабо Верде",
    ukrNameLowCase: "кабо верде",
  },
  {
    name: "Cayman Islands",
    numericCode: "136",
    ukrName: "Кайманові острови",
    ukrNameLowCase: "кайманові острови",
  },
  {
    name: "Central African Republic",
    numericCode: "140",
    ukrName: "Центральноафриканська Республіка",
    ukrNameLowCase: "центральноафриканська республіка",
  },
  {
    name: "Chad",
    numericCode: "148",
    ukrName: "Чад",
    ukrNameLowCase: "чад",
  },
  {
    name: "Chile",
    numericCode: "152",
    ukrName: "Чилі",
    ukrNameLowCase: "чилі",
  },
  {
    name: "China",
    numericCode: "156",
    ukrName: "Китай",
    ukrNameLowCase: "китай",
  },
  {
    name: "Christmas Island",
    numericCode: "162",
    ukrName: "Острів Різдва",
    ukrNameLowCase: "острів різдва",
  },
  {
    name: "Cocos (Keeling) Islands",
    numericCode: "166",
    ukrName: "Кокосові (Кілінг) острови",
    ukrNameLowCase: "кокосові (кілінг) острови",
  },
  {
    name: "Colombia",
    numericCode: "170",
    ukrName: "Колумбія",
    ukrNameLowCase: "колумбія",
  },
  {
    name: "Comoros",
    numericCode: "174",
    ukrName: "Коморські острови",
    ukrNameLowCase: "коморські острови",
  },
  {
    name: "Congo",
    numericCode: "178",
    ukrName: "Конго",
    ukrNameLowCase: "конго",
  },
  {
    name: "Congo (Democratic Republic of the)",
    numericCode: "180",
    ukrName: "Конго (Демократична Республіка)",
    ukrNameLowCase: "конго (демократична республіка)",
  },
  {
    name: "Cook Islands",
    numericCode: "184",
    ukrName: "Острови Кука",
    ukrNameLowCase: "острови кука",
  },
  {
    name: "Costa Rica",
    numericCode: "188",
    ukrName: "Коста-Ріка",
    ukrNameLowCase: "коста-ріка",
  },
  {
    name: "Croatia",
    numericCode: "191",
    ukrName: "Хорватія",
    ukrNameLowCase: "хорватія",
  },
  {
    name: "Cuba",
    numericCode: "192",
    ukrName: "Куба",
    ukrNameLowCase: "куба",
  },
  {
    name: "Curaçao",
    numericCode: "531",
    ukrName: "Кюрасао",
    ukrNameLowCase: "кюрасао",
  },
  {
    name: "Cyprus",
    numericCode: "196",
    ukrName: "Кіпр",
    ukrNameLowCase: "кіпр",
  },
  {
    name: "Czech Republic",
    numericCode: "203",
    ukrName: "Чехія",
    ukrNameLowCase: "чехія",
  },
  {
    name: "Denmark",
    numericCode: "208",
    ukrName: "Данія",
    ukrNameLowCase: "данія",
  },
  {
    name: "Djibouti",
    numericCode: "262",
    ukrName: "Джібуті",
    ukrNameLowCase: "джібуті",
  },
  {
    name: "Dominica",
    numericCode: "212",
    ukrName: "Домініка",
    ukrNameLowCase: "домініка",
  },
  {
    name: "Dominican Republic",
    numericCode: "214",
    ukrName: "Домініканська Республіка",
    ukrNameLowCase: "домініканська республіка",
  },
  {
    name: "Ecuador",
    numericCode: "218",
    ukrName: "Еквадор",
    ukrNameLowCase: "еквадор",
  },
  {
    name: "Egypt",
    numericCode: "818",
    ukrName: "Єгипет",
    ukrNameLowCase: "єгипет",
  },
  {
    name: "El Salvador",
    numericCode: "222",
    ukrName: "Сальвадор",
    ukrNameLowCase: "сальвадор",
  },
  {
    name: "Equatorial Guinea",
    numericCode: "226",
    ukrName: "Екваторіальна Гвінея",
    ukrNameLowCase: "екваторіальна гвінея",
  },
  {
    name: "Eritrea",
    numericCode: "232",
    ukrName: "Еритрея",
    ukrNameLowCase: "еритрея",
  },
  {
    name: "Estonia",
    numericCode: "233",
    ukrName: "Естонія",
    ukrNameLowCase: "естонія",
  },
  {
    name: "Ethiopia",
    numericCode: "231",
    ukrName: "Ефіопія",
    ukrNameLowCase: "ефіопія",
  },
  {
    name: "Falkland Islands (Malvinas)",
    numericCode: "238",
    ukrName: "Фолклендські (Мальвінські) острови",
    ukrNameLowCase: "фолклендські (мальвінські) острови",
  },
  {
    name: "Faroe Islands",
    numericCode: "234",
    ukrName: "Фарерські острови",
    ukrNameLowCase: "фарерські острови",
  },
  {
    name: "Fiji",
    numericCode: "242",
    ukrName: "Фіджі",
    ukrNameLowCase: "фіджі",
  },
  {
    name: "Finland",
    numericCode: "246",
    ukrName: "Фінляндія",
    ukrNameLowCase: "фінляндія",
  },
  {
    name: "France",
    numericCode: "250",
    ukrName: "Франція",
    ukrNameLowCase: "франція",
  },
  {
    name: "French Guiana",
    numericCode: "254",
    ukrName: "Французька Гвіана",
    ukrNameLowCase: "французька гвіана",
  },
  {
    name: "French Polynesia",
    numericCode: "258",
    ukrName: "Французька Полінезія",
    ukrNameLowCase: "французька полінезія",
  },
  {
    name: "French Southern Territories",
    numericCode: "260",
    ukrName: "Французькі південні території",
    ukrNameLowCase: "французькі південні території",
  },
  {
    name: "Gabon",
    numericCode: "266",
    ukrName: "Габон",
    ukrNameLowCase: "габон",
  },
  {
    name: "Gambia",
    numericCode: "270",
    ukrName: "Гамбія",
    ukrNameLowCase: "гамбія",
  },
  {
    name: "Georgia",
    numericCode: "268",
    ukrName: "Грузія",
    ukrNameLowCase: "грузія",
  },
  {
    name: "Germany",
    numericCode: "276",
    ukrName: "Німеччина",
    ukrNameLowCase: "німеччина",
  },
  {
    name: "Ghana",
    numericCode: "288",
    ukrName: "Гана",
    ukrNameLowCase: "гана",
  },
  {
    name: "Gibraltar",
    numericCode: "292",
    ukrName: "Гібралтар",
    ukrNameLowCase: "гібралтар",
  },
  {
    name: "Greece",
    numericCode: "300",
    ukrName: "Греція",
    ukrNameLowCase: "греція",
  },
  {
    name: "Greenland",
    numericCode: "304",
    ukrName: "Гренландія",
    ukrNameLowCase: "гренландія",
  },
  {
    name: "Grenada",
    numericCode: "308",
    ukrName: "Гренада",
    ukrNameLowCase: "гренада",
  },
  {
    name: "Guadeloupe",
    numericCode: "312",
    ukrName: "Гваделупа",
    ukrNameLowCase: "гваделупа",
  },
  {
    name: "Guam",
    numericCode: "316",
    ukrName: "Гуам",
    ukrNameLowCase: "гуам",
  },
  {
    name: "Guatemala",
    numericCode: "320",
    ukrName: "Гватемала",
    ukrNameLowCase: "гватемала",
  },
  {
    name: "Guernsey",
    numericCode: "831",
    ukrName: "Гернсі",
    ukrNameLowCase: "гернсі",
  },
  {
    name: "Guinea",
    numericCode: "324",
    ukrName: "Гвінея",
    ukrNameLowCase: "гвінея",
  },
  {
    name: "Guinea-Bissau",
    numericCode: "624",
    ukrName: "Гвінея-Бісау",
    ukrNameLowCase: "гвінея-бісау",
  },
  {
    name: "Guyana",
    numericCode: "328",
    ukrName: "Гаяна",
    ukrNameLowCase: "гаяна",
  },
  {
    name: "Haiti",
    numericCode: "332",
    ukrName: "Гаїті",
    ukrNameLowCase: "гаїті",
  },
  {
    name: "Heard Island and McDonald Islands",
    numericCode: "334",
    ukrName: "Острови Херд і Макдональд",
    ukrNameLowCase: "острови херд і макдональд",
  },
  {
    name: "Vatican City",
    numericCode: "336",
    ukrName: "Ватикан",
    ukrNameLowCase: "ватикан",
  },
  {
    name: "Honduras",
    numericCode: "340",
    ukrName: "Гондурас",
    ukrNameLowCase: "гондурас",
  },
  {
    name: "Hungary",
    numericCode: "348",
    ukrName: "Угорщина",
    ukrNameLowCase: "угорщина",
  },
  {
    name: "Hong Kong",
    numericCode: "344",
    ukrName: "Гонконг",
    ukrNameLowCase: "гонконг",
  },
  {
    name: "Iceland",
    numericCode: "352",
    ukrName: "ісландія",
    ukrNameLowCase: "ісландія",
  },
  {
    name: "India",
    numericCode: "356",
    ukrName: "індія",
    ukrNameLowCase: "індія",
  },
  {
    name: "Indonesia",
    numericCode: "360",
    ukrName: "індонезія",
    ukrNameLowCase: "індонезія",
  },
  {
    name: "Ivory Coast",
    numericCode: "384",
    ukrName: "Берег Слонової Кістки",
    ukrNameLowCase: "берег слонової кістки",
  },
  {
    name: "Iran (Islamic Republic of)",
    numericCode: "364",
    ukrName: "іран (ісламська Республіка)",
    ukrNameLowCase: "іран (ісламська республіка)",
  },
  {
    name: "Iraq",
    numericCode: "368",
    ukrName: "ірак",
    ukrNameLowCase: "ірак",
  },
  {
    name: "Ireland",
    numericCode: "372",
    ukrName: "ірландія",
    ukrNameLowCase: "ірландія",
  },
  {
    name: "Isle of Man",
    numericCode: "833",
    ukrName: "Острів Мен",
    ukrNameLowCase: "острів мен",
  },
  {
    name: "Israel",
    numericCode: "376",
    ukrName: "ізраїль",
    ukrNameLowCase: "ізраїль",
  },
  {
    name: "Italy",
    numericCode: "380",
    ukrName: "італія",
    ukrNameLowCase: "італія",
  },
  {
    name: "Jamaica",
    numericCode: "388",
    ukrName: "Ямайка",
    ukrNameLowCase: "ямайка",
  },
  {
    name: "Japan",
    numericCode: "392",
    ukrName: "Японія",
    ukrNameLowCase: "японія",
  },
  {
    name: "Jersey",
    numericCode: "832",
    ukrName: "Джерсі",
    ukrNameLowCase: "джерсі",
  },
  {
    name: "Jordan",
    numericCode: "400",
    ukrName: "Джордан",
    ukrNameLowCase: "джордан",
  },
  {
    name: "Kazakhstan",
    numericCode: "398",
    ukrName: "Казахстан",
    ukrNameLowCase: "казахстан",
  },
  {
    name: "Kenya",
    numericCode: "404",
    ukrName: "Кенія",
    ukrNameLowCase: "кенія",
  },
  {
    name: "Kiribati",
    numericCode: "296",
    ukrName: "Кірібаті",
    ukrNameLowCase: "кірібаті",
  },
  {
    name: "Kuwait",
    numericCode: "414",
    ukrName: "Кувейт",
    ukrNameLowCase: "кувейт",
  },
  {
    name: "Kyrgyzstan",
    numericCode: "417",
    ukrName: "Киргизстан",
    ukrNameLowCase: "киргизстан",
  },
  {
    name: "Lao People's Democratic Republic",
    numericCode: "418",
    ukrName: "Лаоська Народно-Демократична Республіка",
    ukrNameLowCase: "лаоська народно-демократична республіка",
  },
  {
    name: "Latvia",
    numericCode: "428",
    ukrName: "Латвія",
    ukrNameLowCase: "латвія",
  },
  {
    name: "Lebanon",
    numericCode: "422",
    ukrName: "Ліван",
    ukrNameLowCase: "ліван",
  },
  {
    name: "Lesotho",
    numericCode: "426",
    ukrName: "Лесото",
    ukrNameLowCase: "лесото",
  },
  {
    name: "Liberia",
    numericCode: "430",
    ukrName: "Ліберія",
    ukrNameLowCase: "ліберія",
  },
  {
    name: "Libya",
    numericCode: "434",
    ukrName: "Лівія",
    ukrNameLowCase: "лівія",
  },
  {
    name: "Liechtenstein",
    numericCode: "438",
    ukrName: "Ліхтенштейн",
    ukrNameLowCase: "ліхтенштейн",
  },
  {
    name: "Lithuania",
    numericCode: "440",
    ukrName: "Литва",
    ukrNameLowCase: "литва",
  },
  {
    name: "Luxembourg",
    numericCode: "442",
    ukrName: "Люксембург",
    ukrNameLowCase: "люксембург",
  },
  {
    name: "Macao",
    numericCode: "446",
    ukrName: "Макао",
    ukrNameLowCase: "макао",
  },
  {
    name: "North Macedonia",
    numericCode: "807",
    ukrName: "Північна Македонія",
    ukrNameLowCase: "північна македонія",
  },
  {
    name: "Madagascar",
    numericCode: "450",
    ukrName: "Мадагаскар",
    ukrNameLowCase: "мадагаскар",
  },
  {
    name: "Malawi",
    numericCode: "454",
    ukrName: "Малаві",
    ukrNameLowCase: "малаві",
  },
  {
    name: "Malaysia",
    numericCode: "458",
    ukrName: "Малайзія",
    ukrNameLowCase: "малайзія",
  },
  {
    name: "Maldives",
    numericCode: "462",
    ukrName: "Мальдіви",
    ukrNameLowCase: "мальдіви",
  },
  {
    name: "Mali",
    numericCode: "466",
    ukrName: "Малі",
    ukrNameLowCase: "малі",
  },
  {
    name: "Malta",
    numericCode: "470",
    ukrName: "Мальта",
    ukrNameLowCase: "мальта",
  },
  {
    name: "Marshall Islands",
    numericCode: "584",
    ukrName: "Маршаллові острови",
    ukrNameLowCase: "маршаллові острови",
  },
  {
    name: "Martinique",
    numericCode: "474",
    ukrName: "Мартиніка",
    ukrNameLowCase: "мартиніка",
  },
  {
    name: "Mauritania",
    numericCode: "478",
    ukrName: "Мавританія",
    ukrNameLowCase: "мавританія",
  },
  {
    name: "Mauritius",
    numericCode: "480",
    ukrName: "Маврикій",
    ukrNameLowCase: "маврикій",
  },
  {
    name: "Mayotte",
    numericCode: "175",
    ukrName: "Майотта",
    ukrNameLowCase: "майотта",
  },
  {
    name: "Mexico",
    numericCode: "484",
    ukrName: "Мексика",
    ukrNameLowCase: "мексика",
  },
  {
    name: "Micronesia (Federated States of)",
    numericCode: "583",
    ukrName: "Мікронезія (Федеративні Штати)",
    ukrNameLowCase: "мікронезія (федеративні штати)",
  },
  {
    name: "Moldova (Republic of)",
    numericCode: "498",
    ukrName: "Молдова (Республіка)",
    ukrNameLowCase: "молдова (республіка)",
  },
  {
    name: "Monaco",
    numericCode: "492",
    ukrName: "Монако",
    ukrNameLowCase: "монако",
  },
  {
    name: "Mongolia",
    numericCode: "496",
    ukrName: "Монголія",
    ukrNameLowCase: "монголія",
  },
  {
    name: "Montenegro",
    numericCode: "499",
    ukrName: "Чорногорія",
    ukrNameLowCase: "чорногорія",
  },
  {
    name: "Montserrat",
    numericCode: "500",
    ukrName: "Монсеррат",
    ukrNameLowCase: "монсеррат",
  },
  {
    name: "Morocco",
    numericCode: "504",
    ukrName: "Марокко",
    ukrNameLowCase: "марокко",
  },
  {
    name: "Mozambique",
    numericCode: "508",
    ukrName: "Мозамбік",
    ukrNameLowCase: "мозамбік",
  },
  {
    name: "Myanmar",
    numericCode: "104",
    ukrName: "М'янма",
    ukrNameLowCase: "м'янма",
  },
  {
    name: "Namibia",
    numericCode: "516",
    ukrName: "Намібія",
    ukrNameLowCase: "намібія",
  },
  {
    name: "Nauru",
    numericCode: "520",
    ukrName: "Науру",
    ukrNameLowCase: "науру",
  },
  {
    name: "Nepal",
    numericCode: "524",
    ukrName: "Непал",
    ukrNameLowCase: "непал",
  },
  {
    name: "Netherlands",
    numericCode: "528",
    ukrName: "Нідерланди",
    ukrNameLowCase: "нідерланди",
  },
  {
    name: "New Caledonia",
    numericCode: "540",
    ukrName: "Нова Каледонія",
    ukrNameLowCase: "нова каледонія",
  },
  {
    name: "New Zealand",
    numericCode: "554",
    ukrName: "Нова Зеландія",
    ukrNameLowCase: "нова зеландія",
  },
  {
    name: "Nicaragua",
    numericCode: "558",
    ukrName: "Нікарагуа",
    ukrNameLowCase: "нікарагуа",
  },
  {
    name: "Niger",
    numericCode: "562",
    ukrName: "Нігер",
    ukrNameLowCase: "нігер",
  },
  {
    name: "Nigeria",
    numericCode: "566",
    ukrName: "Нігерія",
    ukrNameLowCase: "нігерія",
  },
  {
    name: "Niue",
    numericCode: "570",
    ukrName: "Ніуе",
    ukrNameLowCase: "ніуе",
  },
  {
    name: "Norfolk Island",
    numericCode: "574",
    ukrName: "Острів Норфолк",
    ukrNameLowCase: "острів норфолк",
  },
  {
    name: "Korea (Democratic People's Republic of)",
    numericCode: "408",
    ukrName: "Корейська Народно-Демократична Республіка",
    ukrNameLowCase: "корейська народно-демократична республіка",
  },
  {
    name: "Northern Mariana Islands",
    numericCode: "580",
    ukrName: "Північні Маріанські острови",
    ukrNameLowCase: "північні маріанські острови",
  },
  {
    name: "Norway",
    numericCode: "578",
    ukrName: "Норвегія",
    ukrNameLowCase: "норвегія",
  },
  {
    name: "Oman",
    numericCode: "512",
    ukrName: "Оман",
    ukrNameLowCase: "оман",
  },
  {
    name: "Pakistan",
    numericCode: "586",
    ukrName: "Пакистан",
    ukrNameLowCase: "пакистан",
  },
  {
    name: "Palau",
    numericCode: "585",
    ukrName: "Палау",
    ukrNameLowCase: "палау",
  },
  {
    name: "Palestine, State of",
    numericCode: "275",
    ukrName: "Палестина, держава",
    ukrNameLowCase: "палестина, держава",
  },
  {
    name: "Panama",
    numericCode: "591",
    ukrName: "Панама",
    ukrNameLowCase: "панама",
  },
  {
    name: "Papua New Guinea",
    numericCode: "598",
    ukrName: "Папуа Нова Гвінея",
    ukrNameLowCase: "папуа нова гвінея",
  },
  {
    name: "Paraguay",
    numericCode: "600",
    ukrName: "Парагвай",
    ukrNameLowCase: "парагвай",
  },
  {
    name: "Peru",
    numericCode: "604",
    ukrName: "Перу",
    ukrNameLowCase: "перу",
  },
  {
    name: "Philippines",
    numericCode: "608",
    ukrName: "Філіппіни",
    ukrNameLowCase: "філіппіни",
  },
  {
    name: "Pitcairn",
    numericCode: "612",
    ukrName: "Піткерн",
    ukrNameLowCase: "піткерн",
  },
  {
    name: "Poland",
    numericCode: "616",
    ukrName: "Польща",
    ukrNameLowCase: "польща",
  },
  {
    name: "Portugal",
    numericCode: "620",
    ukrName: "Португалія",
    ukrNameLowCase: "португалія",
  },
  {
    name: "Puerto Rico",
    numericCode: "630",
    ukrName: "Пуерто-Ріко",
    ukrNameLowCase: "пуерто-ріко",
  },
  {
    name: "Qatar",
    numericCode: "634",
    ukrName: "Катар",
    ukrNameLowCase: "катар",
  },
  {
    name: "Republic of Kosovo",
    numericCode: "926",
    ukrName: "Республіка Косово",
    ukrNameLowCase: "республіка косово",
  },
  {
    name: "Réunion",
    numericCode: "638",
    ukrName: "Реюньйон",
    ukrNameLowCase: "реюньйон",
  },
  {
    name: "Romania",
    numericCode: "642",
    ukrName: "Румунія",
    ukrNameLowCase: "румунія",
  },
  {
    name: "Russian Federation",
    numericCode: "643",
    ukrName: "Російська Федерація",
    ukrNameLowCase: "російська федерація",
  },
  {
    name: "Rwanda",
    numericCode: "646",
    ukrName: "Руанда",
    ukrNameLowCase: "руанда",
  },
  {
    name: "Saint Barthélemy",
    numericCode: "652",
    ukrName: "Сен-Бартелемі",
    ukrNameLowCase: "сен-бартелемі",
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    numericCode: "654",
    ukrName: "Свята Єлена, Вознесіння і Трістан да Кунья",
    ukrNameLowCase: "свята єлена, вознесіння і трістан да кунья",
  },
  {
    name: "Saint Kitts and Nevis",
    numericCode: "659",
    ukrName: "Сент-Кітс і Невіс",
    ukrNameLowCase: "сент-кітс і невіс",
  },
  {
    name: "Saint Lucia",
    numericCode: "662",
    ukrName: "Сент-Люсія",
    ukrNameLowCase: "сент-люсія",
  },
  {
    name: "Saint Martin (French part)",
    numericCode: "663",
    ukrName: "Сен-Мартен (французька частина)",
    ukrNameLowCase: "сен-мартен (французька частина)",
  },
  {
    name: "Saint Pierre and Miquelon",
    numericCode: "666",
    ukrName: "Сен-П'єр і Мікелон",
    ukrNameLowCase: "сен-п'єр і мікелон",
  },
  {
    name: "Saint Vincent and the Grenadines",
    numericCode: "670",
    ukrName: "Сент-Вінсент і Гренадини",
    ukrNameLowCase: "сент-вінсент і гренадини",
  },
  {
    name: "Samoa",
    numericCode: "882",
    ukrName: "Самоа",
    ukrNameLowCase: "самоа",
  },
  {
    name: "San Marino",
    numericCode: "674",
    ukrName: "Сан-Марино",
    ukrNameLowCase: "сан-марино",
  },
  {
    name: "Sao Tome and Principe",
    numericCode: "678",
    ukrName: "Сан-Томе і Принсіпі",
    ukrNameLowCase: "сан-томе і принсіпі",
  },
  {
    name: "Saudi Arabia",
    numericCode: "682",
    ukrName: "Саудівська Аравія",
    ukrNameLowCase: "саудівська аравія",
  },
  {
    name: "Senegal",
    numericCode: "686",
    ukrName: "Сенегал",
    ukrNameLowCase: "сенегал",
  },
  {
    name: "Serbia",
    numericCode: "688",
    ukrName: "Сербія",
    ukrNameLowCase: "сербія",
  },
  {
    name: "Seychelles",
    numericCode: "690",
    ukrName: "Сейшельські острови",
    ukrNameLowCase: "сейшельські острови",
  },
  {
    name: "Sierra Leone",
    numericCode: "694",
    ukrName: "Сьєрра-Леоне",
    ukrNameLowCase: "сьєрра-леоне",
  },
  {
    name: "Singapore",
    numericCode: "702",
    ukrName: "Сінгапур",
    ukrNameLowCase: "сінгапур",
  },
  {
    name: "Sint Maarten (Dutch part)",
    numericCode: "534",
    ukrName: "Сінт-Мартен (голландська частина)",
    ukrNameLowCase: "сінт-мартен (голландська частина)",
  },
  {
    name: "Slovakia",
    numericCode: "703",
    ukrName: "Словаччина",
    ukrNameLowCase: "словаччина",
  },
  {
    name: "Slovenia",
    numericCode: "705",
    ukrName: "Словенія",
    ukrNameLowCase: "словенія",
  },
  {
    name: "Solomon Islands",
    numericCode: "090",
    ukrName: "Соломонові Острови",
    ukrNameLowCase: "соломонові острови",
  },
  {
    name: "Somalia",
    numericCode: "706",
    ukrName: "Сомалі",
    ukrNameLowCase: "сомалі",
  },
  {
    name: "South Africa",
    numericCode: "710",
    ukrName: "Південна Африка",
    ukrNameLowCase: "південна африка",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    numericCode: "239",
    ukrName: "Південна Джорджія та Південні Сандвічеві острови",
    ukrNameLowCase: "південна джорджія та південні сандвічеві острови",
  },
  {
    name: "Korea (Republic of)",
    numericCode: "410",
    ukrName: "Корея (Республіка)",
    ukrNameLowCase: "корея (республіка)",
  },
  {
    name: "Spain",
    numericCode: "724",
    ukrName: "іспанія",
    ukrNameLowCase: "іспанія",
  },
  {
    name: "Sri Lanka",
    numericCode: "144",
    ukrName: "Шрі-Ланка",
    ukrNameLowCase: "шрі-ланка",
  },
  {
    name: "Sudan",
    numericCode: "729",
    ukrName: "Судан",
    ukrNameLowCase: "судан",
  },
  {
    name: "South Sudan",
    numericCode: "728",
    ukrName: "Південний Судан",
    ukrNameLowCase: "південний судан",
  },
  {
    name: "Suriname",
    numericCode: "740",
    ukrName: "Суринам",
    ukrNameLowCase: "суринам",
  },
  {
    name: "Svalbard and Jan Mayen",
    numericCode: "744",
    ukrName: "Шпіцберген і Ян-Майєн",
    ukrNameLowCase: "шпіцберген і ян-майєн",
  },
  {
    name: "Swaziland",
    numericCode: "748",
    ukrName: "Свазіленд",
    ukrNameLowCase: "свазіленд",
  },
  {
    name: "Sweden",
    numericCode: "752",
    ukrName: "Швеція",
    ukrNameLowCase: "швеція",
  },
  {
    name: "Switzerland",
    numericCode: "756",
    ukrName: "Швейцарія",
    ukrNameLowCase: "швейцарія",
  },
  {
    name: "Syrian Arab Republic",
    numericCode: "760",
    ukrName: "Сирійська Арабська Республіка",
    ukrNameLowCase: "сирійська арабська республіка",
  },
  {
    name: "Taiwan",
    numericCode: "158",
    ukrName: "Тайвань",
    ukrNameLowCase: "тайвань",
  },
  {
    name: "Tajikistan",
    numericCode: "762",
    ukrName: "Таджикистан",
    ukrNameLowCase: "таджикистан",
  },
  {
    name: "Tanzania, United Republic of",
    numericCode: "834",
    ukrName: "Танзанія, Об'єднана Республіка",
    ukrNameLowCase: "танзанія, об'єднана республіка",
  },
  {
    name: "Thailand",
    numericCode: "764",
    ukrName: "Таїланд",
    ukrNameLowCase: "таїланд",
  },
  {
    name: "Timor-Leste",
    numericCode: "626",
    ukrName: "Тимор-Лешті",
    ukrNameLowCase: "тимор-лешті",
  },
  {
    name: "Togo",
    numericCode: "768",
    ukrName: "Того",
    ukrNameLowCase: "того",
  },
  {
    name: "Tokelau",
    numericCode: "772",
    ukrName: "Токелау",
    ukrNameLowCase: "токелау",
  },
  {
    name: "Tonga",
    numericCode: "776",
    ukrName: "Тонга",
    ukrNameLowCase: "тонга",
  },
  {
    name: "Trinidad and Tobago",
    numericCode: "780",
    ukrName: "Тринідад і Тобаго",
    ukrNameLowCase: "тринідад і тобаго",
  },
  {
    name: "Tunisia",
    numericCode: "788",
    ukrName: "Туніс",
    ukrNameLowCase: "туніс",
  },
  {
    name: "Turkey",
    numericCode: "792",
    ukrName: "Туреччина",
    ukrNameLowCase: "туреччина",
  },
  {
    name: "Turkmenistan",
    numericCode: "795",
    ukrName: "Туркменістан",
    ukrNameLowCase: "туркменістан",
  },
  {
    name: "Turks and Caicos Islands",
    numericCode: "796",
    ukrName: "Острови Теркс і Кайкос",
    ukrNameLowCase: "острови теркс і кайкос",
  },
  {
    name: "Tuvalu",
    numericCode: "798",
    ukrName: "Тувалу",
    ukrNameLowCase: "тувалу",
  },
  {
    name: "Uganda",
    numericCode: "800",
    ukrName: "Уганда",
    ukrNameLowCase: "уганда",
  },
  {
    name: "Ukraine",
    numericCode: "804",
    ukrName: "Україна",
    ukrNameLowCase: "україна",
  },
  {
    name: "United Arab Emirates",
    numericCode: "784",
    ukrName: "Об'єднані Арабські Емірати",
    ukrNameLowCase: "об'єднані арабські емірати",
  },
  {
    name: "United Kingdom of Great Britain and Northern Ireland",
    numericCode: "826",
    ukrName: "Сполучене Королівство Великої Британії та Північної ірландії",
    ukrNameLowCase:
      "сполучене королівство великої британії та північної ірландії",
  },
  {
    name: "United States of America",
    numericCode: "840",
    ukrName: "Сполучені Штати Америки (США)",
    ukrNameLowCase: "сполучені штати америки",
  },
  {
    name: "Uruguay",
    numericCode: "858",
    ukrName: "Уругвай",
    ukrNameLowCase: "уругвай",
  },
  {
    name: "Uzbekistan",
    numericCode: "860",
    ukrName: "Узбекистан",
    ukrNameLowCase: "узбекистан",
  },
  {
    name: "Vanuatu",
    numericCode: "548",
    ukrName: "Вануату",
    ukrNameLowCase: "вануату",
  },
  {
    name: "Venezuela (Bolivarian Republic of)",
    numericCode: "862",
    ukrName: "Венесуела (Боліваріанська Республіка)",
    ukrNameLowCase: "венесуела (боліваріанська республіка)",
  },
  {
    name: "Vietnam",
    numericCode: "704",
    ukrName: "В'єтнам",
    ukrNameLowCase: "в'єтнам",
  },
  {
    name: "Wallis and Futuna",
    numericCode: "876",
    ukrName: "Уолліс і Футуна",
    ukrNameLowCase: "уолліс і футуна",
  },
  {
    name: "Western Sahara",
    numericCode: "732",
    ukrName: "Західна Сахара",
    ukrNameLowCase: "західна сахара",
  },
  {
    name: "Yemen",
    numericCode: "887",
    ukrName: "Ємен",
    ukrNameLowCase: "ємен",
  },
  {
    name: "Zambia",
    numericCode: "894",
    ukrName: "Замбія",
    ukrNameLowCase: "замбія",
  },
  {
    name: "Zimbabwe",
    numericCode: "716",
    ukrName: "Зімбабве",
    ukrNameLowCase: "зімбабве",
  },
];
